### ISSUE TITLE
Support for Matlab tables

### ISSUE THREAD

**Issue by jbfaden** [gradusnikov/jmatio#8]
I have a .mat file one of my scientist end users provided me which has a two tables within it, and the library doesn't seem to find it.  In Matlab 2021a when loading the file I get two "tables":

![image](https://github.com/gradusnikov/jmatio/assets/3385225/4a1995cc-54fd-4c99-8d5f-9623af1adc92)

But the jmatio library doesn't return these.  I can provide the file, but not on a website since the file may contain unpublished data.

Is this a bug or are tables not supported?  We were able to work around the problem by exporting the data to a different file from within Matlab, but I would like for my software to read this type of data in the future.

**Comment by jbfaden** [comment]
Also I'll note while walking through your code with the Netbeans debugger, I could see there were multiple objects with the name "@".  Subsequent objects with the same name appear to be ignored, see https://github.com/gradusnikov/jmatio/blob/a42b41921735ac3f7b3e62fdd90c9982b1a0a015/src/main/java/com/jmatio/io/MatFileReader.java#L445 .

**Comment by ennerf** [comment]
@jbfaden I totally forgot that I setup a notification on this repo at one point. I don't know whether this repo receives updates anymore, but I maintain a different MAT library ([MFL](https://github.com/HebiRobotics/MFL)) and can provide some info on this.

The [Mathworks documentation](https://www.mathworks.com/help/pdf_doc/matlab/matfile_format.pdf) only provides information on the most basic types like matrices or cell arrays. All the newer object types (e.g. `string`, `table`, `categoricals`, etc.) are stored in a completely undocumented format in the MCOS Subsystem (SciPy calls it [__function_workspace](https://stackoverflow.com/a/56943418/3574093)) that has only been partially reverse engineered and understood.

If I remember correctly `jmatio` does not implement any of it, but the later fork [MatFileRW](https://github.com/diffplug/matfilerw) has at least partial support for MCOS. It would still take a good amount of work to go from there to actually support tables though.

The simplest way would be to convert the table to a supported type like struct or cell array before saving.

**Comment by jbfaden** [comment]
Thanks for getting back to me so quickly.  Typically we don't have control over how the file was created, a collaborator sends my end user a .mat file assuming they have Matlab, and often they don't.  This is where it would be nice if my software (autoplot.org) could read the file, since it's freely available.  I'll have a look at the other library you mentioned.  Thanks for getting back to me.
